[package]
name = "serde-aes"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"
uuid = "1.11.0"
